"""Conditioned feature transformations used by AdaViP.

Each transform keeps a shared path and adds a compact per-example low-rank
residual whose parameters are generated by the HyperNet. This captures the
task-conditioned encoder behavior without materializing a full dense network
for every sample.
"""

from __future__ import annotations

import math
from typing import Sequence, Tuple

import torch
from torch import Tensor, nn


class HyperNetwork(nn.Module):
    """Generate per-example transformation parameters from a context vector."""

    def __init__(self, input_dim: int, output_dim: int, hidden_dim: int = 256):
        super().__init__()
        if input_dim <= 0 or output_dim <= 0 or hidden_dim <= 0:
            raise ValueError("HyperNetwork dimensions must be positive")

        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, output_dim),
        )

        # Start close to the shared path. The small non-zero weight keeps the
        # conditioning path active from the first optimization step.
        nn.init.normal_(self.net[-1].weight, mean=0.0, std=1e-3)
        nn.init.zeros_(self.net[-1].bias)

    def forward(self, context: Tensor) -> Tensor:
        if context.ndim != 2:
            raise ValueError(
                f"HyperNetwork expects [batch, context], got {tuple(context.shape)}"
            )
        return self.net(context)


class ConditionalAffine(nn.Module):
    """Apply a bounded, generated affine modulation to the last dimension."""

    def __init__(self, feature_dim: int, scale_limit: float = 0.5):
        super().__init__()
        if feature_dim <= 0:
            raise ValueError("feature_dim must be positive")
        if scale_limit <= 0:
            raise ValueError("scale_limit must be positive")
        self.feature_dim = feature_dim
        self.scale_limit = scale_limit

    def forward(self, features: Tensor, parameters: Tensor) -> Tensor:
        if features.shape[-1] != self.feature_dim:
            raise ValueError(
                f"Expected feature width {self.feature_dim}, "
                f"got {features.shape[-1]}"
            )
        if parameters.ndim != 2 or parameters.shape[-1] != 2 * self.feature_dim:
            raise ValueError(
                f"Expected parameters [batch, {2 * self.feature_dim}], "
                f"got {tuple(parameters.shape)}"
            )
        if features.shape[0] != parameters.shape[0]:
            raise ValueError("Feature and parameter batch dimensions must match")

        scale_delta, bias = parameters.chunk(2, dim=-1)
        scale = 1.0 + self.scale_limit * torch.tanh(scale_delta)
        while scale.ndim < features.ndim:
            scale = scale.unsqueeze(1)
            bias = bias.unsqueeze(1)
        return features * scale + bias


class GeneratedLowRankLinear(nn.Module):
    """Shared linear path plus a per-example HyperNet-generated low-rank residual."""

    def __init__(self, input_dim: int, output_dim: int, rank: int = 4):
        super().__init__()
        if input_dim <= 0 or output_dim <= 0 or rank <= 0:
            raise ValueError("input_dim, output_dim, and rank must be positive")
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.rank = rank
        self.base = nn.Linear(input_dim, output_dim)
        self.parameter_dim = output_dim * rank + rank * input_dim + output_dim
        self.residual_scale = 1.0 / math.sqrt(rank)

    def forward(self, features: Tensor, parameters: Tensor) -> Tensor:
        if features.shape[-1] != self.input_dim:
            raise ValueError(
                f"Expected input width {self.input_dim}, got {features.shape[-1]}"
            )
        if parameters.ndim != 2 or parameters.shape[-1] != self.parameter_dim:
            raise ValueError(
                f"Expected parameters [batch, {self.parameter_dim}], "
                f"got {tuple(parameters.shape)}"
            )
        if features.shape[0] != parameters.shape[0]:
            raise ValueError("Feature and parameter batch dimensions must match")

        left_width = self.output_dim * self.rank
        right_width = self.rank * self.input_dim
        left, right, bias = torch.split(
            parameters, (left_width, right_width, self.output_dim), dim=-1
        )
        left = left.reshape(-1, self.output_dim, self.rank)
        right = right.reshape(-1, self.rank, self.input_dim)
        bias = bias.unsqueeze(1)

        # First contract the generated right factor with each sequence token,
        # then apply the generated left factor to obtain the residual output.
        low_rank_features = torch.einsum("bri,bti->btr", right, features)
        residual = torch.einsum("bor,btr->bto", left, low_rank_features)
        return self.base(features) + self.residual_scale * residual + bias


class AdaptiveModalityTransform(nn.Module):
    """Generated encoder residual followed by a shared task-invariant decoder."""

    def __init__(self, input_dim: int, latent_dim: int, rank: int = 4):
        super().__init__()
        if input_dim <= 0 or latent_dim <= 0 or rank <= 0:
            raise ValueError("input_dim, latent_dim, and rank must be positive")
        self.input_dim = input_dim
        self.latent_dim = latent_dim
        self.input_norm = nn.LayerNorm(input_dim)
        self.encoder = GeneratedLowRankLinear(input_dim, latent_dim, rank=rank)
        self.parameter_dim = self.encoder.parameter_dim
        self.decoder = nn.Sequential(
            nn.GELU(),
            nn.Linear(latent_dim, latent_dim),
            nn.LayerNorm(latent_dim),
        )

    def forward(self, features: Tensor, parameters: Tensor) -> Tensor:
        if features.shape[-1] != self.input_dim:
            raise ValueError(
                f"Expected input width {self.input_dim}, got {features.shape[-1]}"
            )
        encoded = self.encoder(self.input_norm(features), parameters)
        return self.decoder(encoded)


def split_generated_parameters(
    parameters: Tensor, parameter_widths: Sequence[int]
) -> Tuple[Tuple[Tensor, ...], Tensor]:
    """Split modality and fusion parameters from one HyperNet output."""

    if not parameter_widths or any(width <= 0 for width in parameter_widths):
        raise ValueError("parameter_widths must contain positive values")
    expected_width = sum(parameter_widths)
    if parameters.ndim != 2 or parameters.shape[-1] != expected_width:
        raise ValueError(
            f"Expected generated parameters [batch, {expected_width}], "
            f"got {tuple(parameters.shape)}"
        )
    chunks = parameters.split(tuple(parameter_widths), dim=-1)
    return chunks[:-1], chunks[-1]
