task: vistac_wrist
dataset_path: /data/wangzihao/datasets/manifeel/plug_quan_Aug02
isaacgym_cfg_name: isaacgym_config_power_plug.yaml
run_name: dp_power_plug_tacrgb_seed42
num_demos: 50
num_epochs: 1000
seed: 42
rollout_every: 0
checkpoint_every: 100
val_every: 10
batch_size: 512
num_workers: 8
val_batch_size: 128
val_num_workers: 2
